# Generated by Django 5.0.6 on 2024-05-12 19:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FoodItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('category', models.CharField(choices=[('NO', 'Do Not Eat'), ('LIMIT', 'Limit Intake'), ('FREE', 'Eat Freely')], max_length=5)),
                ('food_type', models.CharField(choices=[('DAIRY', 'Dairy'), ('MEAT_PROTEIN', 'Meat + Protein'), ('FLAVOUR', 'Flavour'), ('VEGGIES', 'Veggies'), ('FRUITS', 'Fruits'), ('GRAINS', 'Grains'), ('BEVVIES', 'Bevvies'), ('SWEETS', 'Sweets'), ('NUTS', 'Nuts'), ('SEEDS', 'Seeds'), ('SNEAKY_SNACKS', 'Sneaky Snacks')], max_length=15)),
                ('details', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='FoodLogEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(auto_now_add=True)),
                ('comments', models.TextField(blank=True)),
                ('food_items', models.ManyToManyField(to='diet_manager.fooditem')),
            ],
        ),
    ]
