# Generated by Django 5.0.6 on 2024-05-12 20:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diet_manager', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fooditem',
            name='food_type',
            field=models.CharField(choices=[('DAIRY', 'Dairy'), ('MEAT_PROTEIN', 'Meat + Protein'), ('FLAVOUR', 'Flavour'), ('VEGGIES', 'Veggies'), ('FRUITS', 'Fruits'), ('GRAINS', 'Grains'), ('BEVVIES', 'Bevvies'), ('SWEETS', 'Sweets'), ('NUTS', 'Nuts'), ('SEEDS', 'Seeds'), ('SNEAKY_SNACKS', 'Sneaky Snacks'), ('FLOURS_STARCHES', 'Flours + Starches')], max_length=15),
        ),
    ]
