# Generated by Django 5.0.6 on 2024-05-13 05:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diet_manager', '0002_alter_fooditem_food_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fooditem',
            name='category',
            field=models.CharField(choices=[('NO', 'Do Not Eat'), ('LIMIT', 'Limit Intake'), ('FREE', 'Eat Freely')], max_length=10),
        ),
    ]
